<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 55ac4bd (fix(ci): remove double curly bracket in success() method)
---
yaml-files:
  - "*.yaml"
  - "*.yml"
  - ".yamllint"
<<<<<<< HEAD

rules:
  anchors: disable
  braces: enable
  brackets: enable
  colons: enable
  commas: enable
  comments:
    level: warning
    require-starting-space: true
    ignore-shebangs: true
    min-spaces-from-content: 1
  comments-indentation:
    level: warning
  document-end: disable
  document-start: disable
  empty-lines: enable
  empty-values: disable
  float-values: disable
  hyphens: enable
  indentation: enable
  key-duplicates: enable
  key-ordering: disable
  line-length: disable
  new-line-at-end-of-file: disable
  new-lines: enable
  octal-values: disable
  quoted-strings: disable
  trailing-spaces: enable
  truthy:
    level: warning
    check-keys: false
=======
extends: default
=======
>>>>>>> 55ac4bd (fix(ci): remove double curly bracket in success() method)

rules:
  anchors: disable
  braces: enable
  brackets: enable
  colons: enable
  commas: enable
  comments:
    level: warning
    require-starting-space: true
    ignore-shebangs: true
    min-spaces-from-content: 1
  comments-indentation:
    level: warning
  document-end: disable
  document-start: disable
  empty-lines: enable
  empty-values: disable
  float-values: disable
  hyphens: enable
  indentation: enable
  key-duplicates: enable
  key-ordering: disable
  line-length: disable
  new-line-at-end-of-file: disable
  new-lines: enable
  octal-values: disable
  quoted-strings: disable
  trailing-spaces: enable
  truthy:
<<<<<<< HEAD
    allowed-values: ["true", "false", "yes", "no", "on", "off"]
  document-start:
    present: false
>>>>>>> 446d5aa (fix(ci): fix command actionlint, playwright wrong runs-on spelling word & yamllint config)
=======
    level: warning
    check-keys: false
>>>>>>> 55ac4bd (fix(ci): remove double curly bracket in success() method)
