import type { Metadata } from "next";
<<<<<<< HEAD
<<<<<<< HEAD
import localFont from "next/font/local";
import "./globals.css";

const inter = localFont({ src: "./../fonts/inter.woff2", weight: "100 900" });
=======
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

>>>>>>> 32d98d4 (Initial commit from Create Next App)
=======
import localFont from "next/font/local";
import "./globals.css";

const inter = localFont({ src: "./../fonts/inter.woff2", weight: "100 900" });
>>>>>>> 0156483 (initial commit)
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 0156483 (initial commit)
    <html
      lang="en"
      className={`${inter.className} scroll-smooth bg-white-secondary`}
    >
      <body className="relative flex min-h-screen flex-col">{children}</body>
<<<<<<< HEAD
=======
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
>>>>>>> 32d98d4 (Initial commit from Create Next App)
=======
>>>>>>> 0156483 (initial commit)
    </html>
  );
}
