import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const inter = localFont({ src: "./../fonts/inter.woff2", weight: "100 900" });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.className} scroll-smooth bg-white-secondary`}
    >
      <body className="relative flex min-h-screen flex-col">{children}</body>
    </html>
  );
}
