name: Build.Validate

on:
<<<<<<< HEAD
<<<<<<< HEAD
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "src/**"
      - "tests/**"
      - "playwright.config.*"
      - "package-lock.json"
      - "package.json"
  pull_request:
    branches: [main]
    paths:
      - "src/**"
      - "tests/**"
      - "playwright.config.*"
      - "package-lock.json"
      - "package.json"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  # 1. Lint GitHub Actions / YAML
  lint-actions:
    name: Validate.Lint.Actions
    uses: anhntinterview/next-boilerplate-251001/.github/workflows/_Validate.Lint.Actions.yaml@ci/setup-workflows

  # 2. Validate PR Title (Conventional Commit)
  lint-pr:
    name: Validate.Lint.PR
    if: ${{ github.event_name == 'pull_request' }}
    uses: anhntinterview/next-boilerplate-251001/.github/workflows/_Validate.Lint.PR.yaml@ci/setup-workflows

  # 3. Node Build + Sonar Scan + Docker Build Validation
  node-build:
    name: Node.Build.Validate
    needs: [lint-actions, lint-pr]
    if: ${{ (github.event_name != 'pull_request' || needs.lint-pr.result == 'success') && needs.lint-actions.result == 'success' }}
    uses: anhntinterview/next-boilerplate-251001/.github/workflows/Node.Build.Validate.yaml@ci/setup-workflows
    with:
      node_version: 20
      project_root_directory: "."
      npmscripts: lint,typecheck,format:check
      run_sonar_scan: true

  # 4. Playwright Tests (E2E)
  playwright:
    name: Playwright.E2E
    needs: [node-build]
    if: ${{needs.node-build.result == 'success'}}
    uses: anhntinterview/next-boilerplate-251001/.github/workflows/playwright.yaml@ci/setup-workflows
=======
    workflow_dispatch:
    pull_request:
        branches: [main]
=======
>>>>>>> ab6b35d (fix(ci): cancel previous commit to focus on current commit is run)
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    # Node Build + Sonar Scan + Docker Build Validation
    node-build:
        name: Node.Build.Validate
        uses: anhntinterview/next-boilerplate-251001/.github/workflows/Node.Build.Validate.yaml@v1
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> b3525a3 (fix: revert)

    # 4. Playwright Tests (E2E)
    playwright:
        name: Playwright.E2E
        needs: [node-build]
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
        uses: next-boilerplate-251001/main/.github/workflows/playwright.yaml@v1
>>>>>>> 5654635 (ci: add reusable workflows and full CI/CD pipeline setup)
=======
        uses: next-boilerplate-251001/.github/workflows/playwright.yaml@v1
>>>>>>> 697e5fa (fix(ci): remove main out of version link)
=======
        uses: next-boilerplate-251001/main/.github/workflows/playwright.yaml@v1
>>>>>>> 614b1ba (fix(ci build): fix format 'owner/repository/' or './' for local workflows)
=======
        uses: next-boilerplate-251001/.github/workflows/playwright.yaml@v1
>>>>>>> 5a30a79 (fix(ci): fix access file path)
=======
        uses: next-boilerplate-251001/main/.github/workflows/playwright.yaml@v1
>>>>>>> 07dbeba (fix(ci): yaml file path)
=======
        uses: anhntinterview/next-boilerplate-251001/.github/workflows/playwright.yaml@v1
>>>>>>> 9e4f382 (fix(ci): yaml file)
=======
>>>>>>> ea075af (fix(ci): remove check lint + playwright to Build.Validate.yaml)
=======
        uses: anhntinterview/next-boilerplate-251001/.github/workflows/playwright.yaml@v1
>>>>>>> b3525a3 (fix: revert)
=======
>>>>>>> c8ae621 (fix: remove lint & playwright to Build.Validate.yaml)
