name: Build.Validate

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    # Node Build + Sonar Scan + Docker Build Validation
    node-build:
        name: Node.Build.Validate
        uses: anhntinterview/next-boilerplate-251001/.github/workflows/Node.Build.Validate.yaml@v1
