name: Next.js Boilerplate 01/10/2025

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Lint
        run: npm run lint

      - name: Type check
        run: npm run typecheck

      - name: Install dependencies
        run: npm ci

      - name: Run Unit Tests (Vitest)
        run: npm run test:coverage

      - name: Run E2E Tests (Playwright)
        run: |
          npx playwright install --with-deps
          npm run build:playwright
          npx next start & sleep 3
          npm run test:playwright

      - name: Run SonarQube Analysis
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/next-boilerplate-251001:latest .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME}}/next-boilerplate-250101:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-test-push

    steps:
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/next-boilerplate-251001:latest
            docker stop next-boilerplate-250101:latest || true
            docker rm next-boilerplate-250101:latest || true
            docker run -d \
              --name next-boilerplate-251001 \
              -p 3000:3000 \
              ${{ secrets.DOCKERHUB_USERNAME }}/next-boilerplate-251001:latest
