name: Create.GitHub.Tag

on:
  workflow_call:
    inputs:
      major:
        required: true
        type: string
      minor:
        required: true
        type: string
      patch:
        required: true
        type: string

jobs:
  create-tags:
    name: Create.GitHub.Tags
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create and push version tags
        env:
          MAJOR: ${{ inputs.major }}
          MINOR: ${{ inputs.minor }}
          PATCH: ${{ inputs.patch }}
        run: |
          set -e
          VERSION="v${MAJOR}.${MINOR}.${PATCH}"
          echo "🏷️ Creating tags for ${VERSION}"

          # Configure Git user
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Fetch latest tags to avoid conflicts
          git fetch --tags

          # Create or update patch tag (v1.2.3)
          git tag -f "${VERSION}"
          git push origin "${VERSION}" --force

          # Create or update minor tag (v1.2)
          git tag -f "v${MAJOR}.${MINOR}"
          git push origin "v${MAJOR}.${MINOR}" --force

          # Create or update major tag (v1)
          git tag -f "v${MAJOR}"
          git push origin "v${MAJOR}" --force

          echo "✅ Tags created:"
          echo "  - ${VERSION}"
          echo "  - v${MAJOR}.${MINOR}"
          echo "  - v${MAJOR}"
