name: NR.Change.Tracking

on:
  workflow_dispatch:
  repository_dispatch:
    types: [tracking-newrelic]

jobs:
  nr-change-tracking:
    name: Report Deployment to New Relic
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: New Relic Change Tracking Marker
        uses: newrelic/deployment-marker-action@v2.3.0
        with:
          apiKey: ${{ secrets.NR_PLATFORM_US_USER_API_KEY }}
          accountId: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}
          guid: ${{ secrets.NR_ENTITY_GUIDE }}
          version: ${{ github.event.client_payload.ref }}
          changelog: "https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md"
          commit: "${{ github.event.client_payload.sha }}"
          description:
            "Deployment to ${{ github.event.client_payload.env }} (${{
            github.event.client_payload.region }})"
          deeplink: "${{ github.event.client_payload.deeplink }}"
          user: "${{ github.actor }}"
          deploymentType: "ROLLING"
          groupId: "${{ github.event.client_payload.application_name }}-${{ github.event.client_payload.ref }}"
