name: Message After PR

on:
  workflow_dispatch:
    inputs:
      manual_docker_tag:
        required: true
        description: Set manual version of docker tag
        type: string
  push:
    branches:
      - main

jobs:
  print-messages:
    runs-on: ubuntu-latest
    steps:
      - name: Print confirmation message
        run: |
          echo "The PR has been merged! Workflow run successfully"
          echo "🔹 Repository: ${{ github.repository }}"
          echo "🔹 Actor: ${{ github.actor }}"
          echo "🔹 Commit SHA: ${{ github.sha }}"
          echo "🔹 Branch: ${{ github.ref_name }}"
